// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace NguyenThuyDung124.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230104014047_Create_Table_NTD0124")]
    partial class CreateTableNTD0124
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("NguyenThuyDung124.Models.CompanyNTD124", b =>
                {
                    b.Property<string>("CompanyId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CompanyId");

                    b.ToTable("CompanyNTD124");
                });

            modelBuilder.Entity("NguyenThuyDung124.Models.NTD0124", b =>
                {
                    b.Property<string>("NTDId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NTDGender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NTDName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("NTDId");

                    b.ToTable("NTD0124");
                });
#pragma warning restore 612, 618
        }
    }
}
